### ISSUE TITLE
useCurrencyFormat

### ISSUE THREAD

**Issue by geekskai** [Baoing/hooks#2]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

**Comment by Baoing** [comment]
https://hooks.baoea.com/?path=/docs/tool-hooks-usecurrencyformat--docs

**Comment by Baoing** [comment]
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

useCurrencyFormat hook在[toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString)的基础上具有增强意义，不仅仅是js层面上的货币转换，接轨Shopify fomat标准 ， 简化了与Shopify的枚举和参数对接，省去业务代码中再去拼凑。

请看参考文档【格式选项部分】
https://hooks.baoea.com/?path=/docs/tool-hooks-usecurrencyformat--docs

Shopify帮助中心对Shopify fomat的描述
https://help.shopify.com/zh-CN/en/manual/international/pricing/currency-formatting
![image](https://github.com/user-attachments/assets/63460c75-da42-4ffe-a3c5-b82be957fcf1)

Shopify fomat标准的表现
![image](https://github.com/user-attachments/assets/39721775-7cf8-44be-8482-9195ab84643d)

![image](https://github.com/user-attachments/assets/d4e749c0-5d0a-4188-a462-7aa6167bf454)

**Comment by geekskai** [comment]
下面的是八种情况都实现的：

const amount = 1134.65;

// 默认货币格式
const amount_default = amount.toLocaleString();
console.log(`{{ amount }}`, amount_default); // "1,134.65"

// 四舍五入，不显示小数位
const amount_no_decimals = amount.toLocaleString(undefined, { maximumFractionDigits: 0 });
console.log(`{{ amount_no_decimals }}`, amount_no_decimals); // "1,135"

// 使用逗号作为千位分隔符
const amount_with_comma_separator = amount.toLocaleString(undefined, { useGrouping: true });
console.log(`{{ amount_with_comma_separator }}`, amount_with_comma_separator); // "1,134.65"

// 不显示小数位且使用逗号作为千位分隔符
const amount_no_decimals_with_comma_separator = amount.toLocaleString(undefined, { maximumFractionDigits: 0, useGrouping: true });
console.log(`{{ amount_no_decimals_with_comma_separator }}`, amount_no_decimals_with_comma_separator); // "1,135"

// 使用撇号作为千位分隔符
const amount_with_apostrophe_separator = amount.toLocaleString("en-US", { useGrouping: true }).replace(/,/g, "'");
console.log(`{{ amount_with_apostrophe_separator }}`, amount_with_apostrophe_separator); // "1'134.65"

// 不显示小数位且使用空格作为千位分隔符
const amount_no_decimals_with_space_separator = amount.toLocaleString("fr-FR", { maximumFractionDigits: 0, useGrouping: true });
console.log(`{{ amount_no_decimals_with_space_separator }}`, amount_no_decimals_with_space_separator); // "1 135"

// 使用空格作为千位分隔符
const amount_with_space_separator = amount.toLocaleString("fr-FR", { useGrouping: true });
console.log(`{{ amount_with_space_separator }}`, amount_with_space_separator); // "1 134,65"

// 使用空格作为千位分隔符，句点作为小数分隔符
const amount_with_period_and_space_separator = amount.toLocaleString("en-GB", { useGrouping: true });
console.log(`{{ amount_with_period_and_space_separator }}`, amount_with_period_and_space_separator); // "1 134.65"

**Comment by geekskai** [comment]
commafy 函数:

这个函数在处理小数时可能会出现问题。例如，对于数字 `1234.56`，它会返回 `1,234.56`，这是正确的。但对于 `1234.5678`，它会返回 `1,234.5,678`。

**Comment by Baoing** [comment]
@geekskai👍👍 感谢宝贵建议，已经对这些进行了改进

https://github.com/Baoing/hooks/commit/a6afa0407bc8d10456db94e765163b6895057f47
